owner: JorisPV
repo: Status
runner: "[self-hosted, linux, ARM64]"
user-agent: jorispv

sites:
  - name: Hydeos
    url: https://hydeos.fr
    maxResponseTime: 500
  - name: Panel - Hydeos
    url: https://pterodactyl.hydeos.fr
    maxResponseTime: 500
  - name: Arragon
    url: https://arragon.hydeos.fr
    maxResponseTime: 500
  - name: Funcraft - Site web
    url: https://www.funcraft.net/fr
    maxResponseTime: 500
  - name: Forum - Funcraft
    url: https://community.funcraft.net/
    maxResponseTime: 500
  - name: Pactify
    url: https://www.pactify.fr/
    maxResponseTime: 500
  - name: AZ-Launcher
    url: https://az-launcher.nz/
    maxResponseTime: 500
  - name: Forum - Ascentia
    url: https://community.ascentia.fr/
    maxResponseTime: 500
  - name: Account - Ascentia
    url: https://account.ascentia.fr/
    maxResponseTime: 500
  - name: Boutique - Ascentia
    url: https://store.ascentia.fr/
    maxResponseTime: 500
  - name: Joris - Perso
    url: https://joris-parmentier.fr
    maxResponseTime: 500
  - name: Joris - Acenox
    url: https://acenox.fr
    maxResponseTime: 500
    
status-website:
  baseUrl: /Status
  name: Status
  theme: night
  
i18n:
  url: "URL"
  status: "Status"
  history: "Historique"
  uptime: "Uptime"
  up: "🟩 Up"
  degraded: "🟨 Dégradé"
  down: "🟥 Down"
  responseTimeGraphAlt: "Temps de réponse"
  ms: "ms"
  responseTime: "Temps de réponse"
  responseTimeDay: "24 heures - Temps de réponse"
  responseTimeWeek: "7 jours - Temps de réponse"
  responseTimeMonth: "30 jours - Temps de réponse"
  responseTimeYear: "365 jours - Temps de réponse"
  uptimeDay: "Dernières 24 heures"
  uptimeWeek: "Dernière semaine"
  uptimeMonth: "Dernier mois"
  uptimeYear: "Dernière année"
  liveStatus: "Status"
  liveStatusHtmlComment: "<!--live status-->"
  allSystemsOperational: "Aucun problème n'est détecté"
  degradedPerformance: "Un service est dégradé"
  completeOutage: "Un service est DOWN"
  partialOutage: "Un service est dégradé"
  activeIncidents: "Liste des incidents"
  incidentReport: "Incident #$NUMBER →"
  activeIncidentSummary: "Ouvert le $DATE"
  incidentTitle: "Détails de l'incident numéro $NUMBER"
  incidentDetails: "Détails de l'incident"
  incidentFixed: "Corrigé"
  incidentOngoing: "En cours"
  incidentOpenedAt: "Ouvert le"
  incidentClosedAt: "Clôturé le"
  incidentViewOnGitHub: "Plus d'infos sur Github"
  incidentCommentSummary: "Commentaire → $DATE par $AUTHOR"
  incidentBack: "← Retour en arrière"
  pastIncidents: "Incidents précédents"
  pastIncidentsResolved: "Résolu en $MINUTES minutes avec $POSTS posts"
  overallUptime: "SLA: $UPTIME"
  overallUptimeTitle: "SLA"
  averageResponseTime: "Temps de réponse: $TIMEms"
  averageResponseTimeTitle: "Temps de réponse"
  sevelDayResponseTime: "Temps de réponse sous 7 jours"
  responseTimeMs: "Temps de réponse en ms"
  loading: "Chargement"
  footer: "Site utilisant [Upptime](https://upptime.js.org)"
  errorHome: "Retour en arrière"
  duration24H: "24h"
  duration7D: "7j"
  duration30D: "30j"
  duration1Y: "365j"
  durationAll: "toujours"
